config/routes.rb
Nomadpm::Application.routes.draw do
  
  

  devise_for :users

  constraints(Subdomain) do
    
    resources :projects do
      resources :stories do
        resources :comments
        resources :tasks
        resources :attachment
        resources :labels
      end
    end
    
    resources :stories, only: [:new, :create]
    resources :iterations
    resources :users
    resources :story_types, path: "story-types"
    resources :states
    
    root to: "iterations#index"
  end
  
  resources :teams, only: [:create]
  root to: "home#start"
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  audited
  
  belongs_to :team
  has_many :stories
  has_and_belongs_to_many :users
  has_many :labels, as: :labelable
  
  attr_accessible :name
  
  validates_presence_of :team, :name
  
  extend FriendlyId
  friendly_id :name, use: :slugged
  
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  include ScopeToTeam
end

app/views/projects/_form.html.haml
= simple_form_for(resource) do |f|
  = f.input :name

  .form-actions
    = f.submit class: "btn btn-primary"

app/views/projects/edit.html.haml
= title("Update Project Settings")
= render "form"

app/views/projects/index.html.haml
- title("Projects")

app/views/projects/new.html.haml
= title("Create a Project")
= render "form"

app/views/projects/show.html.haml
= title(resource.name)

%h4 Stories
= link_to "New Story", new_project_story_path(resource)
= render "stories/list", stories: resource.stories